/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eg.edu.alexu.csd.oop.calculator.cs60;

import javax.swing.JOptionPane;

import eg.edu.alexu.csd.oop.calculator.Calculator;
import java.awt.Toolkit;

/**
 *
 * @author Mohamed Mashaal
 */
public class CalculatorGUI extends javax.swing.JFrame {

  private Calculator manager = new CalculatorImp();

  /**
   * Creates new form NewJFrame.
   */
  public CalculatorGUI() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(
        CalculatorGUI.class.getResource(
            "/eg/edu/alexu/csd/oop/calculator/cs60/asset.png")));
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the
   * form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    formulaArea = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    resultArea = new javax.swing.JLabel();
    delBtn = new javax.swing.JButton();
    num4Btn = new javax.swing.JButton();
    num1Btn = new javax.swing.JButton();
    mltBtn = new javax.swing.JButton();
    num2Btn = new javax.swing.JButton();
    num3Btn = new javax.swing.JButton();
    divBtn = new javax.swing.JButton();
    num5Btn = new javax.swing.JButton();
    num6Btn = new javax.swing.JButton();
    num7Btn = new javax.swing.JButton();
    num8Btn = new javax.swing.JButton();
    num9Btn = new javax.swing.JButton();
    equalBtn = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    prevBtn = new javax.swing.JButton();
    nextBtn = new javax.swing.JButton();
    plusBtn = new javax.swing.JButton();
    mnsBtn = new javax.swing.JButton();
    dotBtn = new javax.swing.JButton();
    num0Btn = new javax.swing.JButton();
    saveBtn = new javax.swing.JButton();
    loadBtn = new javax.swing.JButton();

    setDefaultCloseOperation(
        javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Calculator");
    setResizable(false);

    formulaArea.setBackground(new java.awt.Color(255, 255, 255));
    formulaArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    formulaArea.setHorizontalAlignment(
        javax.swing.SwingConstants.CENTER);
    formulaArea.setBorder(new javax.swing.border.LineBorder(
        new java.awt.Color(0, 0, 0), 3, true));
    formulaArea.setOpaque(true);

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("=");

    resultArea.setBackground(new java.awt.Color(255, 255, 255));
    resultArea.setHorizontalAlignment(
        javax.swing.SwingConstants.CENTER);
    resultArea.setBorder(new javax.swing.border.LineBorder(
        new java.awt.Color(0, 0, 0), 2, true));
    resultArea.setOpaque(true);

    delBtn.setText("Del");
    delBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delBtnActionPerformed(evt);
      }
    });

    num4Btn.setText("4");
    num4Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num4BtnActionPerformed(evt);
      }
    });

    num1Btn.setText("1");
    num1Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num1BtnActionPerformed(evt);
      }
    });

    mltBtn.setText("*");
    mltBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mltBtnActionPerformed(evt);
      }
    });

    num2Btn.setText("2");
    num2Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num2BtnActionPerformed(evt);
      }
    });

    num3Btn.setText("3");
    num3Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num3BtnActionPerformed(evt);
      }
    });

    divBtn.setText("/");
    divBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        divBtnActionPerformed(evt);
      }
    });

    num5Btn.setText("5");
    num5Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num5BtnActionPerformed(evt);
      }
    });

    num6Btn.setText("6");
    num6Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num6BtnActionPerformed(evt);
      }
    });

    num7Btn.setText("7");
    num7Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num7BtnActionPerformed(evt);
      }
    });

    num8Btn.setText("8");
    num8Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num8BtnActionPerformed(evt);
      }
    });

    num9Btn.setText("9");
    num9Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num9BtnActionPerformed(evt);
      }
    });

    equalBtn.setText("=");
    equalBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        equalBtnActionPerformed(evt);
      }
    });

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
        "asset.png"))); // NOI18N

    prevBtn.setText("Prev");
    prevBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        prevBtnActionPerformed(evt);
      }
    });

    nextBtn.setText("Next");
    nextBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nextBtnActionPerformed(evt);
      }
    });

    plusBtn.setText("+");
    plusBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusBtnActionPerformed(evt);
      }
    });

    mnsBtn.setText("-");
    mnsBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mnsBtnActionPerformed(evt);
      }
    });

    dotBtn.setText(".");
    dotBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dotBtnActionPerformed(evt);
      }
    });

    num0Btn.setText("0");
    num0Btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        num0BtnActionPerformed(evt);
      }
    });

    saveBtn.setText("Save");
    saveBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveBtnActionPerformed(evt);
      }
    });

    loadBtn.setText("Load");
    loadBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loadBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
        getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(formulaArea,
                    javax.swing.GroupLayout.Alignment.TRAILING,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                    layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                409,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                    .addGroup(layout
                                        .createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                            javax.swing.GroupLayout.Alignment.TRAILING,
                                            layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                    .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                num4Btn,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                79,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(
                                                                num5Btn,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                79,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                num1Btn,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                79,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(
                                                                num2Btn,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                79,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout
                                                    .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout
                                                        .createSequentialGroup()
                                                        .addGap(13,
                                                            13,
                                                            13)
                                                        .addComponent(
                                                            num6Btn,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            79,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout
                                                        .createSequentialGroup()
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(
                                                            num3Btn,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            79,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(
                                            javax.swing.GroupLayout.Alignment.TRAILING,
                                            layout
                                                .createSequentialGroup()
                                                .addComponent(num7Btn,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    79,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(
                                                    javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(num8Btn,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    79,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(
                                                    javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(num9Btn,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    80,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout
                                        .createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.LEADING,
                                            false)
                                        .addGroup(layout
                                            .createSequentialGroup()
                                            .addGroup(layout
                                                .createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    false)
                                                .addComponent(divBtn,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                                .addComponent(plusBtn,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    61,
                                                    Short.MAX_VALUE))
                                            .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout
                                                .createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    false)
                                                .addGroup(layout
                                                    .createSequentialGroup()
                                                    .addComponent(
                                                        mltBtn,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        61,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(
                                                        delBtn,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        69,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout
                                                    .createSequentialGroup()
                                                    .addComponent(
                                                        mnsBtn,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        61,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(
                                                        dotBtn,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))))
                                        .addGroup(
                                            javax.swing.GroupLayout.Alignment.TRAILING,
                                            layout
                                                .createSequentialGroup()
                                                .addComponent(num0Btn,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                                .addPreferredGap(
                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(
                                                    equalBtn,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    100,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                    .addGroup(layout
                                        .createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(prevBtn,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            249,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout
                                            .createSequentialGroup()
                                            .addComponent(saveBtn,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                122,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(loadBtn,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                120,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(5, 5, 5)
                                    .addGroup(layout
                                        .createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.LEADING,
                                            false)
                                        .addComponent(nextBtn,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE)
                                        .addGroup(
                                            javax.swing.GroupLayout.Alignment.TRAILING,
                                            layout
                                                .createSequentialGroup()
                                                .addComponent(jLabel2,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    106,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(
                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(
                                                    resultArea,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    125,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addContainerGap()));
    layout.setVerticalGroup(layout.createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                124,
                Short.MAX_VALUE)
            .addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(formulaArea,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                55,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(saveBtn,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)
                .addComponent(resultArea,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    39,
                    Short.MAX_VALUE)
                .addComponent(jLabel2,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    39,
                    Short.MAX_VALUE)
                .addComponent(loadBtn,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE))
            .addGap(17, 17, 17)
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(prevBtn,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    60,
                    Short.MAX_VALUE)
                .addComponent(nextBtn,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE))
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num1Btn,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            62,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num2Btn,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            62,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num3Btn,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            62,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(num4Btn,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            62,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num6Btn,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                62,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num5Btn,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                62,
                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(divBtn,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            62,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mltBtn,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            62,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delBtn,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            62,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(plusBtn,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE)
                        .addComponent(mnsBtn,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE)
                        .addComponent(dotBtn,
                            javax.swing.GroupLayout.Alignment.TRAILING,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE))))
            .addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(equalBtn,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7Btn,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        62,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8Btn,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        62,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9Btn,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        62,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(num0Btn,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE))
            .addContainerGap()));

    pack();
  }// </editor-fold>

  private void printChar(String x) {
    String currentText = formulaArea.getText();
    currentText += x;
    formulaArea.setText(currentText);
  }

  private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {
    StringBuilder result = new StringBuilder(formulaArea.getText());
    formulaArea.setText((result.length() - 1 >= 0) ? result
        .deleteCharAt(result.length() - 1).toString() : "");
  }

  private void num1BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("1");
  }

  private void mltBtnActionPerformed(java.awt.event.ActionEvent evt) {
    printChar("*");
  }

  private void divBtnActionPerformed(java.awt.event.ActionEvent evt) {
    printChar("/");
  }

  private void num4BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("4");
  }

  private void prevBtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    String res = manager.prev();
    if (res == null) {
      JOptionPane.showMessageDialog(null,
          "No previous Element !!!",
          "Error",
          JOptionPane.WARNING_MESSAGE);
    } else {
      formulaArea.setText(res);
    }
  }

  private void nextBtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    String res = manager.next();
    if (res == null) {
      JOptionPane.showMessageDialog(null,
          "No next Element !!!",
          "Error",
          JOptionPane.WARNING_MESSAGE);
    } else {
      formulaArea.setText(res);
    }
  }

  private void equalBtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    String formula = formulaArea.getText();
    try {
      manager.input(formula);
      String result = manager.getResult();
      resultArea.setText(result);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null,
          "Wrong expression form ... Please input an expression in the form (x [ + , - , * , / ] y ) \n For example : 5+4",
          "Error",
          JOptionPane.WARNING_MESSAGE);
    }
  }

  private void num2BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("2");
  }

  private void num3BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("3");
  }

  private void num5BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("5");
  }

  private void num6BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("6");
  }

  private void num7BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("7");
  }

  private void num8BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("8");
  }

  private void num9BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("9");
  }

  private void plusBtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("+");
  }

  private void mnsBtnActionPerformed(java.awt.event.ActionEvent evt) {
    printChar("-");
  }

  private void num0BtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    printChar("0");
  }

  private void dotBtnActionPerformed(java.awt.event.ActionEvent evt) {
    printChar(".");
  }

  private void saveBtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    try {
      manager.save();
      JOptionPane.showMessageDialog(null,
          "File has been saved",
          "File Saving",
          JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null,
          "Error Saving File",
          "File Saving",
          JOptionPane.WARNING_MESSAGE);
    }
  }

  private void loadBtnActionPerformed(
      java.awt.event.ActionEvent evt) {
    try {
      manager.load();
      formulaArea.setText(manager.current());
      // resultArea.setText(manager.getResult());
      JOptionPane.showMessageDialog(null,
          "File has been loaded",
          "File Loaded",
          JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null,
          "No File to load",
          "Loading File Problem",
          JOptionPane.WARNING_MESSAGE);
    }
  }

  /**
   * @param args
   *          the command line arguments
   */
  public static void main(String [] args) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting
    // code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
     * html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CalculatorGUI.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CalculatorGUI.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CalculatorGUI.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CalculatorGUI.class
          .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new CalculatorGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify
  private javax.swing.JButton delBtn;
  private javax.swing.JButton divBtn;
  private javax.swing.JButton dotBtn;
  private javax.swing.JButton equalBtn;
  private javax.swing.JLabel formulaArea;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JButton loadBtn;
  private javax.swing.JButton mltBtn;
  private javax.swing.JButton mnsBtn;
  private javax.swing.JButton nextBtn;
  private javax.swing.JButton num0Btn;
  private javax.swing.JButton num1Btn;
  private javax.swing.JButton num2Btn;
  private javax.swing.JButton num3Btn;
  private javax.swing.JButton num4Btn;
  private javax.swing.JButton num5Btn;
  private javax.swing.JButton num6Btn;
  private javax.swing.JButton num7Btn;
  private javax.swing.JButton num8Btn;
  private javax.swing.JButton num9Btn;
  private javax.swing.JButton plusBtn;
  private javax.swing.JButton prevBtn;
  private javax.swing.JLabel resultArea;
  private javax.swing.JButton saveBtn;
  // End of variables declaration
}
